// <auto-generated />
namespace Course_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dropTrainerBirthday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropTrainerBirthday));
        
        string IMigrationMetadata.Id
        {
            get { return "202204212325591_dropTrainerBirthday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
